

//  return Math.max.apply(null,[a,b,c]); 
// }
//    console.log(largestNum(23,45,18))

// function sum (numOne, numTwo) {
//   console.log(numOne + numTwo)  
//   return numOne + numTwo ;
// } 
// sum(303, 689)

// function largestNum(a, b, c,){
  

// function evenOdd(num){
//     if (num % 2 === 0){
//         return true;
//     }else {
//         return false;
//     }    
// } 

// console.log(evenOdd(9))

function str (sentence){
    console.log(sentence)
          if (sentence <=20 ) {
              return string.concat( str + str)
          }else {
             return sentence.slice(0,11)  
          }   
}
console.log(str("Serenity now, Insanity Later"))